### ISSUE TITLE
Incorrect string 

### ISSUE THREAD

**Issue by simplelive** [phenotips/variant-store#13]
OUTPUT:

![Uploading aa.jpg . . .]()

FILE:
org.phenotips.variantstore.input.csv.CSVIterator.java

CODE:

for (String field : csvRecordIterator.next()) {

```
        CSVColumn column = CSVColumn.values()[i++];

        System.out.println("column:\t" + column);

        switch (column) {

            case CHROM:

                System.out.println("CHROM field:\t" + field.trim());

                variant.setReferenceName(field);

                break;
```

**Comment by simplelive** [comment]
OUTPUT:

![aa](https://cloud.githubusercontent.com/assets/2071172/6890801/a844dafa-d6e4-11e4-92d5-40b48cb39298.jpg)

**Comment by meatcar** [comment]
unable to reproduce.
